#!/bin/bash
# Report Generator Skill - Main Script
# Generates professional reports with Vercel-inspired design

set -e

# Paths
BASE_DIR="$HOME/.openclaw/workspace"
SKILL_DIR="$BASE_DIR/skills/report-generator"
TEMPLATE_DIR="$SKILL_DIR/templates"
DATE=$(date +%Y-%m-%d")
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Load CSS template
load_css() {
    if [ -f "$TEMPLATE_DIR/styles/main.css" ]; then
        cat "$TEMPLATE_DIR/styles/main.css"
    else
        # Fallback basic CSS
        cat << 'EOF'
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #000000;
    color: #EAEAEA;
    line-height: 1.6;
    padding: 20px;
}
EOF
    fi
}

# Generate HTML report
generate_html() {
    local report_type="$1"
    local data="$2"
    local output_dir="$3"
    
    local output_file="$output_dir/report-$DATE.html"
    local html_file="$output_dir/index.html"
    
    mkdir -p "$output_dir"
    
    echo -e "${BLUE}Generating $report_type HTML...${NC}"
    
    # Build HTML
    local css=$(load_css)
    cat > "$output_file" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$report_type - $DATE</title>
    <meta name="description" content="Professional report generated by OpenClaw">
    <style>
        $css
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="header-brand">
                <span class="brand-icon">📊</span>
                <span class="brand-name">$report_type</span>
            </div>
            <h1 class="header-title">Report Generated</h1>
            <div class="header-meta">
                <span class="date">$DATE</span>
                <span class="separator">•</span>
                <span class="time">$TIMESTAMP</span>
            </div>
        </header>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">Report Generated</div>
                <div class="stat-label">Status</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">Ready</div>
                <div class="stat-label">Action Required</div>
            </div>
        </div>
        
        <div class="section">
            <h2 class="section-title">Report Data</h2>
            <div class="card">
                <div class="card-content">
                    <pre class="code-block"><code>$data</code></pre>
                </div>
            </div>
        </div>
        
        <footer>
            <p>Generated by <a href="https://duet-company.github.io">duyetbot</a> — AI Employee 1 at Duet Company</p>
            <p style="margin-top: 8px;">Report generated using Report Generator Skill</p>
            <p style="margin-top: 8px; color: #5E6AD2;">To publish to here.now, run the publish script in the output directory</p>
        </footer>
    </div>
    
    <script>
        // Simple fade-in animation
        document.addEventListener('DOMContentLoaded', function() {
            document.body.classList.add('fade-in');
        });
    </script>
</body>
</html>
EOF
    
    echo -e "${GREEN}✅ Generated: $output_file${NC}"
    
    # Copy to index.html for here.now
    cp "$output_file" "$html_file"
    
    echo "$output_dir" > "$output_dir/.hereenow-latest"
}

# Publish to here.now
publish_here_now() {
    local output_dir="$1"
    
    echo -e "${BLUE}Publishing to here.now...${NC}"
    
    cd "$output_dir"
    
    # Try to use here.now skill
    if command -v bash &>/dev/null && [ -f "$BASE_DIR/skills/here-now/scripts/publish.sh" ]; then
        bash "$BASE_DIR/skills/here-now/scripts/publish.sh" "index.html" 2>&1 | tail -5
    else
        echo -e "${YELLOW}⚠️ here.now script not found, skipping publish${NC}"
        return 1
    fi
    
    # Get URL from state file
    if [ -f ".herenow/state.json" ]; then
        local url=$(python3 -c "
import json
try:
    with open('.herenow/state.json', 'r') as f:
        data = json.load(f)
        publishes = data.get('publishes', {})
        if publishes:
            first_key = list(publishes.keys())[0]
            url = publishes[first_key].get('siteUrl', 'N/A')
            print(url)
        else:
            print('N/A')
except Exception as e:
    print(f'Error: {e}')
" 2>/dev/null)
        
        if [ "$url" != "N/A" ]; then
            echo -e "${GREEN}✅ Published: $url${NC}"
            echo "$url" > "$output_dir/latest-url.txt"
            echo "$url" > "$output_dir/.hereenow-latest"
        else
            echo -e "${YELLOW}⚠️ Failed to get URL${NC}"
        return 1
    fi
}

# Generate email template
generate_email() {
    local report_type="$1"
    local data="$2"
    local url="$3"
    
    echo -e "${BLUE}Generating email template...${NC}"
    
    cat << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #000000;
            color: #EAEAEA;
            line-height: 1.6;
            padding: 20px;
            max-width: 600px;
            margin: 0 auto;
        }
        .header {
            background: #0070F3;
            padding: 30px;
            text-align: center;
            border-radius: 8px;
        }
        .header h1 {
            color: white;
            margin: 0;
            font-size: 1.8rem;
        }
        .content {
            background: #111111;
            padding: 30px;
            border-radius: 8px;
            margin: 20px 0;
            color: #EAEAEA;
        }
        pre {
            background: #18181B;
            border-radius: 8px;
            padding: 20px;
            overflow-x: auto;
            font-family: 'SF Mono', monospace;
            font-size: 0.9rem;
        }
        .cta {
            text-align: center;
            margin-top: 30px;
        }
        .cta a {
            display: inline-block;
            background: #0070F3;
            color: white;
            padding: 14px 32px;
            border-radius: 6px;
            text-decoration: none;
            font-weight: 600;
        }
        .footer {
            text-align: center;
            color: #5E6AD2;
            margin-top: 30px;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>$report_type</h1>
    </div>
    
    <div class="content">
        <pre>$data</pre>
    </div>
    
    <div class="cta">
        <a href="$url">View Full Report →</a>
    </div>
    
    <div class="footer">
        <p>Generated at $TIMESTAMP</p>
    </div>
</body>
</html>
EOF
}

# Generate telegram message
generate_telegram() {
    local report_type="$1"
    local data="$2"
    local url="$3"
    
    echo -e "${BLUE}Telegram message preview:${NC}"
    echo ""
    echo "📊 $report_type — $DATE"
    echo ""
    echo "$data"
    echo ""
    echo "🌐 Full Report: $url"
    echo ""
    echo "---"
}

# Main function
main() {
    local action="${1:-help}"
    local report_type="${2:-daily-report}"
    local data="${3:-}"
    local output_dir="${4:-$BASE_DIR/daily-reports}"
    
    case "$action" in
        generate)
            if [ -z "$data" ]; then
                echo -e "${RED}Error: Data parameter required${NC}"
                echo "Usage: $0 generate <report-type> <data> [output-dir]"
                exit 1
            fi
            
            generate_html "$report_type" "$data" "$output_dir"
            ;;
            
        publish)
            publish_here_now "$output_dir"
            ;;
            
        email)
            if [ -z "$data" ] || [ -z "$3" ]; then
                echo -e "${RED}Error: Data and URL parameters required${NC}"
                echo "Usage: $0 email <report-type> <data> <url>"
                exit 1
            fi
            
            generate_email "$report_type" "$data" "$3"
            ;;
            
        telegram)
            if [ -z "$data" ] || [ -z "$3" ]; then
                echo -e "${RED}Error: Data and URL parameters required${NC}"
                echo "Usage: $0 telegram <report-type> <data> <url>"
                exit 1
            fi
            
            generate_telegram "$report_type" "$data" "$3"
            ;;
            
        full)
            generate_html "$report_type" "$data" "$output_dir"
            publish_here_now "$output_dir"
            ;;
            
        help|--help|-h)
            cat << EOF
Report Generator Skill - Vercel Dashboard Design
=============================================

Usage: $0 <action> [options]

Actions:
  generate   Generate HTML report from data
  publish    Publish to here.now
  email      Generate email template
  telegram   Generate Telegram message
  full       Generate, publish, and return URL

Options:
  --report-type <type>     Report type (daily, health, news, etc.)
  --data <data>          Report data (JSON or text)
  --output-dir <dir>       Output directory
  --url <url>              here.now URL

Examples:
  $0 generate --report-type daily --data '{...}' --output-dir ~/reports
  $0 full --report-type health --data 'System healthy'
  $0 telegram --report-type news --data 'AI news items...' --url https://xxx.here.now/
  
Supported Report Types:
  - daily-report: Comprehensive daily overview
  - health-report: System health monitoring
  - ai-news: AI news briefing
  - polymarket-daily: Polymarket daily briefing
  - polymarket-weekly: Polymarket weekly digest
  - task-list: Task progress tracking
  - milestone: Milestone achievements
  - summary: Summary/overview report

Design Features:
  - Vercel dashboard aesthetic (clean, minimal)
  - Unified color palette
  - Responsive design (mobile-first)
  - Email HTML templates (client-safe)
  - Telegram markdown messages
  - Here.now publishing
  - Beautiful data visualization

EOF
            ;;
            
        *)
            echo -e "${RED}Unknown action: $action${NC}"
            echo "Use: $0 help"
            exit 1
            ;;
    esac
}

# Run main
main "$@"
