#!/bin/bash
# Unified Report Generator
# Single template system for all cron job reports
# Usage: ./generate-report.sh <report-type> <data-file>

set -e

# Paths
BASE_DIR="$HOME/.openclaw/workspace"
TEMPLATE_DIR="$BASE_DIR/templates"
DATE=$(date +%Y-%m-%d)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to generate HTML report
generate_html_report() {
    local report_type="$1"
    local title="$2"
    local content_file="$3"
    local output_dir="$4"
    local meta_description="$5"
    
    local output_file="$output_dir/report-$DATE.html"
    local state_file="$output_dir/.herenow/state.json"
    
    mkdir -p "$output_dir/.herenow"
    
    echo "Generating $report_type HTML..." > /dev/null
    
    # Read content
    local content=""
    if [ -f "$content_file" ]; then
        content=$(cat "$content_file" 2>/dev/null || echo "")
    fi
    
    # Read CSS template
    local css_template=""
    if [ -f "$TEMPLATE_DIR/base-styles.css" ]; then
        css_template=$(cat "$TEMPLATE_DIR/base-styles.css")
    fi
    
    # Generate HTML
    cat > "$output_file" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title - $DATE</title>
    <meta name="description" content="$meta_description">
    <style>
        $css_template
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>$title</h1>
            <div class="header-subtitle">$DATE</div>
        </header>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value" id="stats-count">0</div>
                <div class="stat-label">Items</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">24h</div>
                <div class="stat-label">Coverage</div>
            </div>
        </div>
        
        <div class="section">
            <div class="item-content">
$content
            </div>
        </div>
        
        <footer>
            <p>Generated by duyetbot — AI Employee 1 at Duet Company</p>
            <p style="margin-top: 8px;">Report generated at $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>
        </footer>
    </div>
    
    <script>
        // Update stats count
        document.addEventListener('DOMContentLoaded', function() {
            const contentDiv = document.querySelector('.item-content');
            const items = contentDiv ? contentDiv.querySelectorAll('.item, .card, code-block').length : 0;
            document.getElementById('stats-count').textContent = items;
        });
    </script>
</body>
</html>
EOF
    
    echo "✅ Generated: $output_file"
    
    # Publish to here.now
    cd "$output_dir"
    bash "$TEMPLATE_DIR/../skills/here-now/scripts/publish.sh" "$output_file" 2>/dev/null || {
        echo "⚠️ Publishing failed, here.now script not found"
        URL="N/A"
    }
    
    # Get URL
    if [ -f "$state_file" ]; then
        URL=$(python3 -c "import json; f=open('$state_file'); d=json.load(f); print(d.get('publishes', {}).get(list(d.get('publishes', {}).keys())[0] if d.get('publishes') else 'N/A', {}).get('siteUrl', 'N/A'))" 2>/dev/null || echo "N/A")
        if [ "$URL" != "N/A" ]; then
            echo "✅ Published: $URL"
            echo "$URL" > "$output_dir/latest-url.txt"
        else
            echo "⚠️ Failed to get URL"
        fi
    else
        URL="N/A"
        echo "⚠️ State file not found"
    fi
    
    # Output for Telegram
    echo ""
    echo "📊 $report_type - $DATE"
    echo ""
    echo "$title"
    echo ""
    echo "$content"
    echo ""
    if [ "$URL" != "N/A" ]; then
        echo "🌐 Full Report: $URL"
    fi
}

# Main dispatch
case "${1:-help}" in
    --help|-h)
        cat << EOF
Unified Report Generator - Single Template for All Reports

Usage: $0 <report-type> <title> <content> <output-dir> <meta-description>

Report Types:
  ai-news       - Daily AI news briefing
  blog-post     - Blog post with full content
  health        - System health dashboard
  polymarket-daily  - Polymarket daily briefing
  polymarket-weekly - Polymarket weekly digest

Examples:
  $0 ai-news "Daily AI News" content.md ai-news-daily-page "Daily AI news briefing"
  $0 blog-post "Title" blog.md daily-blog-post "Technical blog post"

All reports use:
- Unified dark theme
- Consistent color palette
- Responsive design
- Professional typography
EOF
        ;;
    
    ai-news)
        generate_html_report "Daily AI News" "Daily AI News" "$2" "ai-news-daily-page" "Daily AI news briefing covering latest developments"
        ;;
        
    blog-post)
        generate_html_report "$2" "$2" "$3" "$4" "Blog post: $2"
        ;;
        
    health)
        generate_html_report "System Health" "System Health" "$2" "system-health" "System health monitoring dashboard"
        ;;
        
    polymarket-daily)
        generate_html_report "Polymarket Daily Briefing" "Polymarket Daily Briefing" "$2" "polymarket-daily-briefing" "Daily briefing of trending markets and movers"
        ;;
        
    polymarket-weekly)
        generate_html_report "Polymarket Weekly Digest" "Polymarket Weekly Digest" "$2" "polymarket-weekly-digest" "Weekly digest of major categories"
        ;;
        
    *)
        echo -e "${RED}Unknown report type: ${1}${NC}"
        echo ""
        echo "Use: $0 --help"
        exit 1
        ;;
esac
